import { relations, sql } from "drizzle-orm"
import {
  integer,
  varchar,
  pgTable,
  boolean,
  text,
  timestamp,
  pgEnum,
  primaryKey,
  real,
  uniqueIndex,
  type AnyPgColumn
} from "drizzle-orm/pg-core"

export const userRoleEnum = pgEnum("user_role", ["user", "moderator", "admin"])

// --- USERS ---
export type User = typeof usersTable.$inferSelect
export const usersTable = pgTable("users", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  googleId: varchar().unique(undefined, { nulls: "distinct" }),
  name: varchar({ length: 255 }),
  email: varchar({ length: 254 }),
  isAi: boolean().notNull().default(false),
  role: userRoleEnum().notNull().default("user"),
  // Reputation multiplier, stored per user; not yet applied to vote tallies
  weight: real().notNull().default(1),
  createdAt: timestamp({ mode: "string" }).defaultNow().notNull(),
  notifications: boolean().default(false)
})

export const usersTableRelations = relations(usersTable, ({ one, many }) => ({
  definitions: many(definitionsTable),
  comments: many(commentsTable),
  votes: many(votesTable)
}))

// --- TERMS ---
export type Term = typeof termsTable.$inferSelect
export const termsTable = pgTable("terms", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  // authorId: integer().references(() => usersTable.id),
  createdAt: timestamp({ mode: "string" }).defaultNow().notNull(),
  term: text().notNull().unique(),
  // Human-readable public identifier: /vocabulary/<slug> is the resolvable
  // concept IRI. Generated by lib/slug.ts at insert; treat as immutable once
  // set, since published IRIs depend on it.
  slug: text().notNull().unique()
})

export const termsTableRelations = relations(termsTable, ({ one, many }) => ({
  definitions: many(definitionsTable),
  chats: many(chatsTable)
}))

// --- DEFINITIONS ---
export const definitionSourceEnum = pgEnum("definition_source", [
  "classic",
  "interactive"
])

export type Definition = typeof definitionsTable.$inferSelect
export type DefinitionWithAuthor = Definition & { author: User }
export const definitionsTable = pgTable(
  "definitions",
  {
    id: integer().primaryKey().generatedAlwaysAsIdentity(),
    termId: integer()
      .references(() => termsTable.id)
      .notNull(),
    authorId: integer().references(() => usersTable.id),
    definition: text().notNull(),
    example: text().notNull(),
    // LLM that generated this definition; null for human-authored definitions
    model: text(),
    // System prompt the LLM ran with; null for human-authored definitions
    // (or AI definitions that predate prompt tracking)
    prompt: text(),
    // The original definition this one was refined from (accepted AI
    // suggestion); null for originals
    refinedFromId: integer().references((): AnyPgColumn => definitionsTable.id),
    // Which add flow created this definition; interactive definitions get the
    // refine panel and skip the automatic term-level AI definition
    createdVia: definitionSourceEnum().notNull().default("classic"),
    score: integer().notNull().default(0),
    createdAt: timestamp({ mode: "string", withTimezone: true })
      .default(sql`now()`)
      .notNull(),
    updatedAt: timestamp({ mode: "string" }).$onUpdateFn(() => sql`now()`)
  },
  (table) => [
    // One *original* definition per author per term; refined versions
    // (refinedFromId set) are exempt so an accepted suggestion can coexist
    // with the author's original
    uniqueIndex("definitions_author_term_original_unique")
      .on(table.authorId, table.termId)
      .where(sql`${table.refinedFromId} IS NULL`)
  ]
)

export const definitionsTableRelations = relations(
  definitionsTable,
  ({ one, many }) => ({
    term: one(termsTable, {
      fields: [definitionsTable.termId],
      references: [termsTable.id]
    }),
    author: one(usersTable, {
      fields: [definitionsTable.authorId],
      references: [usersTable.id]
    }),
    refinedFrom: one(definitionsTable, {
      fields: [definitionsTable.refinedFromId],
      references: [definitionsTable.id],
      relationName: "refinedVersions"
    }),
    refinedVersions: many(definitionsTable, {
      relationName: "refinedVersions"
    }),
    coauthors: many(coauthorsTable),
    refinements: many(refinementsTable),
    edits: many(editsTable),
    comments: many(commentsTable),
    votes: many(votesTable),
    tags: many(tagsToDefinitions)
  })
)

// --- DEFINITION COAUTHORS ---
// Additional authors beyond definitions.authorId (the primary author) —
// GitHub-style co-attribution. Used when a user accepts an AI suggestion:
// the model's AI user is added here so both appear as authors, and the
// provenance graph derives wasAttributedTo edges for each.
export const coauthorsTable = pgTable(
  "definitionCoauthors",
  {
    definitionId: integer()
      .references(() => definitionsTable.id)
      .notNull(),
    userId: integer()
      .references(() => usersTable.id)
      .notNull()
  },
  (table) => [primaryKey({ columns: [table.definitionId, table.userId] })]
)

export const coauthorsTableRelations = relations(coauthorsTable, ({ one }) => ({
  definition: one(definitionsTable, {
    fields: [coauthorsTable.definitionId],
    references: [definitionsTable.id]
  }),
  user: one(usersTable, {
    fields: [coauthorsTable.userId],
    references: [usersTable.id]
  })
}))

// --- DEFINITION REFINEMENTS ---
// One row per interactive refinement round (= one card in the UI). Kept out
// of chatsTable deliberately: reviseDefinition() replays that whole thread as
// LLM context for the term-level AI definition, so refine turns must not mix
// into it. Provenance is derived from these rows, so they carry the same
// generation stamp as AI chat rows plus decision timestamps.
export const refinementStatusEnum = pgEnum("refinement_status", [
  "pending", // requested, generation not finished
  "suggested", // suggestion ready, awaiting the author's decision
  "accepted", // author accepted; refined definition created/updated
  "kept", // author kept their original
  "superseded", // replaced by a later round (re-evaluation)
  "failed" // generation errored; errorMessage set
])

export type Refinement = typeof refinementsTable.$inferSelect
export const refinementsTable = pgTable("definitionRefinements", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  definitionId: integer()
    .references(() => definitionsTable.id)
    .notNull(),
  round: integer().notNull(),
  // The author feedback that prompted this round; null on round 1
  userComment: text(),
  suggestedDefinition: text(),
  suggestedExample: text(),
  // Generation provenance, same shape as chats: set once the LLM has run
  promptKey: text(),
  promptHash: text(),
  promptText: text(),
  model: text(),
  status: refinementStatusEnum().notNull().default("pending"),
  errorMessage: text(),
  createdAt: timestamp({ mode: "string", withTimezone: true })
    .default(sql`now()`)
    .notNull(),
  // When the suggestion (or failure) landed — the generation activity's end
  // time in the provenance timeline
  suggestedAt: timestamp({ mode: "string", withTimezone: true }),
  // When the author accepted/kept, or the round was superseded
  decidedAt: timestamp({ mode: "string", withTimezone: true })
})

export const refinementsTableRelations = relations(
  refinementsTable,
  ({ one }) => ({
    definition: one(definitionsTable, {
      fields: [refinementsTable.definitionId],
      references: [definitionsTable.id]
    })
  })
)

// --- DEFINITION EDITS ---
export const editsTable = pgTable("definitionEdits", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  definitionId: integer()
    .references(() => definitionsTable.id)
    .notNull(),
  newDefinition: text(),
  definition: text().notNull(), // what the definition used to be
  editedAt: timestamp().defaultNow().notNull()
})

export const editsTableRelations = relations(editsTable, ({ one }) => ({
  definition: one(definitionsTable, {
    fields: [editsTable.definitionId],
    references: [definitionsTable.id]
  })
}))

// --- VOTES ---
export const voteTypeEnum = pgEnum("vote_type", ["up", "down"])

export type Vote = typeof votesTable.$inferSelect
export const votesTable = pgTable(
  "votes",
  {
    definitionId: integer()
      .references(() => definitionsTable.id)
      .notNull(),
    userId: integer()
      .references(() => usersTable.id)
      .notNull(),
    kind: voteTypeEnum().notNull(),
    // Votes cast before 2026-07-19 carry a placeholder equal to their
    // definition's createdAt (the real time was never recorded)
    createdAt: timestamp({ mode: "string", withTimezone: true })
      .default(sql`now()`)
      .notNull()
  },
  (table) => [primaryKey({ columns: [table.definitionId, table.userId] })]
)

export const votesTableRelations = relations(votesTable, ({ one, many }) => ({
  author: one(usersTable, {
    fields: [votesTable.userId],
    references: [usersTable.id]
  }),
  term: one(definitionsTable, {
    fields: [votesTable.definitionId],
    references: [definitionsTable.id]
  })
}))

// --- COMMENTS ---
export type Comment = typeof commentsTable.$inferSelect
export const commentsTable = pgTable("comments", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  definitionId: integer()
    .references(() => definitionsTable.id)
    .notNull(),
  userId: integer()
    .references(() => usersTable.id)
    .notNull(),
  message: text().notNull(),
  createdAt: timestamp({ mode: "string", withTimezone: true })
    .default(sql`now()`)
    .notNull()
})

export const commentsTableRelations = relations(commentsTable, ({ one }) => ({
  author: one(usersTable, {
    fields: [commentsTable.userId],
    references: [usersTable.id]
  }),
  term: one(definitionsTable, {
    fields: [commentsTable.definitionId],
    references: [definitionsTable.id]
  })
}))

// --- TAGS ---
// SKOS mapping relations a tag may assert toward an external ontology class
export const skosMatchEnum = pgEnum("skos_match", [
  "exactMatch",
  "closeMatch",
  "broadMatch",
  "narrowMatch",
  "relatedMatch"
])

export type Tag = typeof tagsTable.$inferSelect
export const tagsTable = pgTable("tags", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  name: text().notNull(),
  // Optional knowledge-organization layer, curated after the fact; plain
  // tags keep working untouched. `scheme` groups curated facet tags (e.g.
  // "facet"); a mapping asserts a SKOS match to a class in an external
  // ontology such as EMMO or PMDco, and flows into the SKOS export.
  scheme: text(),
  mappingIri: text(),
  mappingRelation: skosMatchEnum()
})

export const tagsTableRelations = relations(tagsTable, ({ many }) => ({
  definitions: many(tagsToDefinitions)
}))

export const tagsToDefinitions = pgTable(
  "tagsToTerms",
  {
    definitionId: integer()
      .references(() => definitionsTable.id)
      .notNull(),
    tagId: integer()
      .references(() => tagsTable.id)
      .notNull()
  },
  (table) => [primaryKey({ columns: [table.tagId, table.definitionId] })]
)

export const tagsToTermsRelations = relations(tagsToDefinitions, ({ one }) => ({
  definition: one(definitionsTable, {
    fields: [tagsToDefinitions.definitionId],
    references: [definitionsTable.id]
  }),
  tag: one(tagsTable, {
    fields: [tagsToDefinitions.tagId],
    references: [tagsTable.id]
  })
}))

export const chatTypeEnum = pgEnum("chat_type", ["system", "user"])

export const chatsTable = pgTable("chats", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  termId: integer()
    .references(() => termsTable.id)
    .notNull(),
  role: chatTypeEnum().notNull(),
  // Author of "user" rows; null on "system" rows and on user rows that
  // predate tracking (except where backfilled from a mirrored comment)
  userId: integer().references(() => usersTable.id),
  message: text().notNull(),
  // Generation provenance, set only on AI ("system") rows: which prompt and
  // model produced this output. promptKey is null when SYSTEM_PROMPT raw text
  // was used; promptHash/promptText always identify the exact prompt sent.
  promptKey: text(),
  promptHash: text(),
  promptText: text(),
  model: text(),
  createdAt: timestamp({ mode: "string", withTimezone: true })
    .default(sql`now()`)
    .notNull()
})

export const chatsTableRelations = relations(chatsTable, ({ one }) => ({
  term: one(termsTable, {
    fields: [chatsTable.termId],
    references: [termsTable.id]
  }),
  author: one(usersTable, {
    fields: [chatsTable.userId],
    references: [usersTable.id]
  })
}))
